name: verduras_app
description: A new Flutter project for managing vegetables.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  animated_text_kit: ^4.2.2
  http: ^0.13.5
  provider: ^6.0.5
  path_provider: ^2.0.15
  google_fonts: ^4.0.0
  flutter_staggered_animations: ^1.1.1
  flutter_dotenv: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets: